language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"  
sudo: false

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.cache/pip"

branches:
  only:
    - master
    - development

install: 
  - sudo apt-get -qq update
  - sudo apt-get install maven
  - pip install -U pip wheel
  - pip install -r pip_requirements.txt

env:
  - TYPE=cli           USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=no
  - TYPE=generic-lib   USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=no
  - TYPE=portal-lib    USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=no
  - TYPE=portlet       USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=no
  - TYPE=portlet       USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=yes
  - TYPE=portlet       USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=yes  USE_QBIC_DATABASES=no
  - TYPE=portlet       USE_OPENBIS_RAW_API=no   USE_OPENBIS_CLIENT=yes  USE_QBIC_DATABASES=yes
  - TYPE=portlet       USE_OPENBIS_RAW_API=yes  USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=no
  - TYPE=portlet       USE_OPENBIS_RAW_API=yes  USE_OPENBIS_CLIENT=no   USE_QBIC_DATABASES=yes
  - TYPE=portlet       USE_OPENBIS_RAW_API=yes  USE_OPENBIS_CLIENT=yes  USE_QBIC_DATABASES=no
  - TYPE=portlet       USE_OPENBIS_RAW_API=yes  USE_OPENBIS_CLIENT=yes  USE_QBIC_DATABASES=yes

script: rm -Rf template-test && 
        ./generate.py --no-input --output-dir . --type=$TYPE artifact_id=template-test use_openbis_client=$USE_OPENBIS_CLIENT use_openbis_raw_api=$USE_OPENBIS_CLIENT use_qbic_databases=$USE_QBIC_DATABASES &&
        pytest --cov=./ &&
        mvn --file template-test/pom.xml --settings template-test/.travis.settings.xml cobertura:cobertura

matrix:
  # we will use this job to generate the code coverage report, no need to execute it twice
  exclude:
    - python: "3.6"
      # this value must match EXACTLY as defined, including whitespace between elements!
      env: TYPE=portlet       USE_OPENBIS_RAW_API=yes  USE_OPENBIS_CLIENT=yes  USE_QBIC_DATABASES=yes

jobs:
  include:
    - stage: "Code Coverage"
      # generate only one code coverage report
      python: "3.6"
      env: TYPE=portlet USE_OPENBIS_RAW_API=yes USE_OPENBIS_CLIENT=yes USE_QBIC_DATABASES=yes
      script: "./.travis.sh"
      after_success:
        - codecov      

notifications:
  email:
    on_success: never
    on_failure: never