sudo: false

language: java
jdk:
- openjdk8

cache:
  directories:
  - "$HOME/.m2/repository"

branches:
  only:
  - master
  - development

# no need for extra dependencies outside the normal build cycle with maven
install: true
script: "./.travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn site

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always